server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 路由id，可以任意
        - id: user-service-route
          # 代理的服务地址
          uri: lb://user-service
          # 路由断言： 可以匹配映射路径
          predicates:
#            - Path=/**
            - Path=/api/user/**
          filters:
            # 添加请求路径的前缀
            #- PrefixPath=/user
            #去除请求路径的前缀，1表示过滤一个路径
            - StripPrefix=1
            - MyParam=name

        - id: donet-service-route
          uri: lb://donet-service
          predicates:
            - Path=/api/donet/user/**
          filters:
            - StripPrefix=2
            - PrefixPath=/api

      default-filters:
        - AddResponseHeader=X-Response-Default-MyName, headertest
      globalcors:
        corsConfigurations:
          '[/**]':
            #allowedOrigins: * # 这种写法或者下面的都可以，*表示全部
            allowedOrigins:
              - "http://docs.spring.io"
            allowedMethods:
              - GET



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0